CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) NOT NULL,
  "useremail" varchar(50) UNIQUE,
  "password" varchar(50),
  "age" integer,
  "created_at" timestamp
);

CREATE TABLE "courses" (
  "courses_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "description" varchar(50),
  "level" varchar(50),
  "user_id" integer,
  "categorie_id" integer
);

CREATE TABLE "coursevideo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_title" varchar(50) NOT NULL,
  "course_url" varchar(50),
  "courses_id" int
);

CREATE TABLE "categories" (
  "categorie_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categorie_name" varchar(50) UNIQUE
);

CREATE TABLE "roles" (
  "roles_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "roles_name" varchar(50) NOT NULL
);

CREATE TABLE "userRole" (
  "userRole_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "roles_id" integer
);

ALTER TABLE "userRole" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "userRole" ADD FOREIGN KEY ("roles_id") REFERENCES "roles" ("roles_id");

ALTER TABLE "users" ADD FOREIGN KEY ("user_id") REFERENCES "courses" ("user_id");

ALTER TABLE "coursevideo" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("courses_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("categorie_id") REFERENCES "categories" ("categorie_id");
